Documentation refresh
Ericsson/CodeCheckerEclipsePlugin pull request #201
Opened 2020-01-15 16:35 UTC by Vodorok

2020-01-15 16:37 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/CodeCheckerEclipsePlugin/pullRequest?prid=4827097&bid=16041147)

2020-01-15 17:54 UTC, gyorb requested changes

2020-01-15 17:54 UTC, gyorb commented on readme.md
> +  * Alternatively, extract the release downloaded from Releases page, and use that as an update site.
Wouldn't github just compress the repository ad a zip file? Can that be used as an update site?

2020-01-15 17:54 UTC, gyorb commented on readme.md
> +After the __CodeChecker Nature__  is added to the the project, the plugin can be configured globally in `Window -> Preferences -> CodeChecker` panel. Or for the individual project, from the `right cl
```suggestion
After the __CodeChecker Nature__  is added to the the project, the plugin can be configured globally in `Window -> Preferences -> CodeChecker` panel, or for the individual project, from the `right click context menu -> Properties -> CodeChecker` page.
```

2020-01-15 17:54 UTC, gyorb commented on readme.md
> +In the first section, you select how and which CodeChecker will be used. After that set some analysis related settings. You should build CodeChecker in a __standalone package__ configuration, and add
I think an example would be nice here. I did not found any documentation in the codechecker repo about the standalon package mode (maybe I missed it).
```sh
cd codechecker
make standalone_package
export PATH=$PWD/build/CodeChecker/bin:$PATH
```

2020-01-16 15:55 UTC, Vodorok commented
Thanks @gyorb I've clarified the docs and incorporated your notices.

2020-01-16 15:59 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/CodeCheckerEclipsePlugin/pullRequest?prid=4827097&bid=16041147)

2020-01-23 17:55 UTC, merged